# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: admin
  host: localhost
  port: 5432


development:
  <<: *default
  database: quote_editor_dev

test:
  <<: *default
  database: quote_editor_test

production:
  primary: &primary_production
    <<: *default
    database: quote_editor_production
    username: quote_editor
    password: <%= ENV["MY_QUOTE_EDITOR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: my_quote_editor_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: my_quote_editor_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: my_quote_editor_production_cable
    migrations_paths: db/cable_migrate
